### ISSUE TITLE
Changing activity invite email address

### ISSUE THREAD

**Issue by jessfmason** [Sheffield-Rotherham-Wildlife-Trust/NatureCounts#104]
From Nottinghamshire WT:

Activity invites come from noreply@wildsheffield.com, can this be changed to noreply@nottswildlife.org?

**Comment by simonrolph** [comment]
I think it's an option on the general site settings config page, it will change the email address that all site emails come from.

When you change it, it's worth sending a test email using this site: https://www.mail-tester.com/ by creating a new account with the generated email address. It tells you how likely the email is to get put into spam etc.

I think with Notts WT I didn't manage to talk to the IT person to get an SPF record on their domain (which helps emails not get sent to spam) so I left it as wildsheffield.com but I don't think it really matters about the SPF record.

**Comment by johnvanbreda** [comment]
Also, I'm not sure what domain the site is running from, but it's important that the email's domain and site domain match, otherwise it will increase the chances of the mail being flagged as spam.
