### ISSUE TITLE
Joining an activity without approval

### ISSUE THREAD

**Issue by jessfmason** [Sheffield-Rotherham-Wildlife-Trust/NatureCounts#105]
Another one from Notts WT:

"The Victoria Park Conservation Area activity is set so that anyone can join without needing approval but when the add to my activities button is pressed it leads to a blank page https://record.nottinghamshirewildlife.org/join/victoria-park-conservation-area "

This happens when trying to join via the link from "share a link to this activity", and also when joining via the "explore all activities" page and using the "add to my activities" button.

This is also the case with SRWT activities

**Comment by johnvanbreda** [comment]
@jessfmason sorry I missed you earlier - I was just getting back from a dog walk. I've fixed this by copying over the latest version of a bit of code, so it should be OK now.
