### ISSUE TITLE
Explore activity records - no "next page" "previous page" visible 

### ISSUE THREAD

**Issue by jessfmason** [Sheffield-Rotherham-Wildlife-Trust/NatureCounts#108]

**Comment by johnvanbreda** [comment]
Is this still a problem? Which activities?

**Comment by jessfmason** [comment]
This was reported by Nottingham WT for Victoria Park Conservation Area

**Comment by johnvanbreda** [comment]
Sorry, I didn't set that site up and don't have the admin password. Does it happen for all activities on the Notts WT site?

**Comment by jessfmason** [comment]
Yes all the activities, and it also happens on the SRWT page

It's only on the "species" "families" and "groups tabs of the explore page, the "records" tab has the buttons

**Comment by johnvanbreda** [comment]
This is a limitation of the Elasticsearch system we use for reporting. You can either have the paging buttons, or the sort by species count, but not both. So, if we put the most recorded at the top then we can't have the buttons.
