### ISSUE TITLE
Elasticsearch query failed

### ISSUE THREAD

**Issue by jessfmason** [Sheffield-Rotherham-Wildlife-Trust/NatureCounts#114]
Following the link to "explore activity records" leads to error message "Elasticsearch query failed"

The option to add an "explore activity records" page to a new activity has also disappeared

**Comment by johnvanbreda** [comment]
At some point, the activity explore page configuration had been changed to "lock" it to the Connecting Steps activity. I unlocked it so you can now add it to other activities and the Elasticsearch error seems OK now.
