### ISSUE TITLE
Elastic search explore pages aren't showing iRecord records

### ISSUE THREAD

**Issue by simonrolph** [Sheffield-Rotherham-Wildlife-Trust/NatureCounts#52]
On https://record.wildsheffield.com/explore/all-records I select iRecord as a source:
![image](https://user-images.githubusercontent.com/17750766/115544919-1d4abd00-a29b-11eb-814a-1403a7006ffb.png)

My guess is that because of this line `<input type="hidden" class="es-filter-param" data-es-bool-clause="must" data-es-field="metadata.website.id" data-es-query-type="term" value="119" /> ` the page can't get data from other sources?

They still show up on the old explore pages:
https://record.wildsheffield.com/explore/all-records-v1

![image](https://user-images.githubusercontent.com/17750766/115544838-fe4c2b00-a29a-11eb-9880-a1ec5335ce62.png)

How can we recreate the filters getting records from other sources from within our reserve boundaries in the new elasticsearch pages?

**Comment by johnvanbreda** [comment]
If we can add a rough polygon for the area of records that are of interest to Wild sheffield then we can use that as a filter instead of the website ID. If we just remove the website ID you will see records from across the UK.

**Comment by simonrolph** [comment]
As a well known text file or shapefile? I've made simplified WKT files before using R

**Comment by johnvanbreda** [comment]
I can probably work with both - WKT should be fine if that's easier for you.

**Comment by simonrolph** [comment]
So I think things have moved on a bit because no we're on the latest iform code we can use the website agreements to sort this?

The other Trusts are keen for this to be set up. Can we set it up with SRWT to see how it works?

Here's a WKT of the SRWT's operational area

```
POLYGON ((-1.238374 53.44109, -1.278651 53.3854, -1.29038 53.34253, -1.281288 53.31828, -1.295323 53.31853, -1.288584 53.32622, -1.299072 53.33251, -1.312333 53.33415, -1.308789 53.33215, -1.314958 53.3265, -1.321622 53.32547, -1.328368 53.32891, -1.337751 53.31583, -1.347288 53.31888, -1.361745 53.31852, -1.362656 53.31501, -1.386842 53.3176, -1.392056 53.32264, -1.38666 53.33484, -1.41109 53.342, -1.420868 53.33455, -1.442014 53.33739, -1.451301 53.33133, -1.459932 53.33061, -1.455243 53.32183, -1.467915 53.31713, -1.478422 53.31935, -1.502109 53.31757, -1.531267 53.31062, -1.536916 53.30471, -1.549077 53.30697, -1.558461 53.30537, -1.56185 53.30667, -1.555823 53.31169, -1.561317 53.31586, -1.580535 53.31172, -1.583079 53.31568, -1.578996 53.31668, -1.585032 53.32157, -1.599079 53.31136, -1.601526 53.31819, -1.608836 53.32254, -1.628286 53.31635, -1.632773 53.32081, -1.612228 53.34319, -1.601577 53.34259, -1.590588 53.34594, -1.625605 53.35204, -1.630593 53.35614, -1.663959 53.36687, -1.663293 53.37423, -1.653517 53.3851, -1.654645 53.39291, -1.66809 53.39305, -1.681829 53.40176, -1.694522 53.40114, -1.704966 53.40504, -1.703235 53.41371, -1.708774 53.41742, -1.718208 53.41946, -1.729952 53.41597, -1.739676 53.4209, -1.746737 53.42618, -1.744273 53.43128, -1.749682 53.43876, -1.743681 53.44494, -1.748082 53.45742, -1.745331 53.46217, -1.752415 53.46494, -1.768351 53.46471, -1.780297 53.47482, -1.791136 53.47581, -1.801472 53.48098, -1.783649 53.48478, -1.738708 53.47714, -1.731813 53.49103, -1.719805 53.49247, -1.711182 53.50119, -1.701134 53.50312, -1.688804 53.49908, -1.668511 53.50053, -1.633832 53.49237, -1.614976 53.4906, -1.614483 53.4931, -1.606617 53.49287, -1.566013 53.48606, -1.549633 53.4785, -1.539099 53.46168, -1.540417 53.4561, -1.551383 53.45544, -1.547361 53.44986, -1.551205 53.44618, -1.545837 53.44172, -1.527817 53.43852, -1.513131 53.45147, -1.518133 53.45723, -1.514814 53.46365, -1.507372 53.4666, -1.494498 53.481, -1.494717 53.48631, -1.46385 53.47801, -1.455203 53.47175, -1.450332 53.47764, -1.452162 53.48502, -1.440941 53.49113, -1.427862 53.48583, -1.415034 53.49247, -1.408507 53.50328, -1.396251 53.50527, -1.380069 53.5142, -1.312567 53.51372, -1.309901 53.49781, -1.289063 53.49102, -1.293188 53.48574, -1.301329 53.48345, -1.295988 53.4805, -1.298671 53.4757, -1.280906 53.4784, -1.269732 53.48587, -1.254406 53.48103, -1.249969 53.47637, -1.25932 53.46422, -1.252142 53.45447, -1.258172 53.45552, -1.251778 53.44871, -1.253732 53.44306, -1.250756 53.44074, -1.238374 53.44109))
```

Is this going to be implemented with hidden inputs? like here: https://indicia-docs.readthedocs.io/en/latest/site-building/iform/prebuilt-forms/dynamic-elasticsearch.html#adding-filters-to-the-page-using-html-hidden-inputs

Can we set it up so that filtering by this polygon is only going to affect data from other sources and we'll still be about to see our own data that sits outside the boundary? If not I guess we could set up a different explore page solely for external data?

**Comment by simonrolph** [comment]
Have set up activities with boundaries for operation areas of each WT. Cloned the explore all records page and added iRecord as a data source, made it so that it can only be linked to the boundary activity.

Can't seem to get the group_id parameter to work (https://indicia-docs.readthedocs.io/en/latest/site-building/iform/helpers/elasticsearch-report-helper.html#elasticsearchreporthelper-groupintegration) so the URL has to have the group_id=XXXX but otherwise works fine.

![image](https://user-images.githubusercontent.com/17750766/128221319-ae4c4d9d-6288-4840-a422-20bb72a3f59a.png)

Same changes applied to all partner trust websites.
