### ISSUE TITLE
Removing an attribute from a survey form which you made required means the data can't be input

### ISSUE THREAD

**Issue by simonrolph** [Sheffield-Rotherham-Wildlife-Trust/NatureCounts#71]
Eg this issue when I removed a Grid name attribute from the survey form and then tried to submit data to the form

```
cUrl POST request failed. Please check cUrl is installed on the server and the $base_url setting is correct.
URL:https://warehouse1.indicia.org.uk/index.php/services/data/save
Server response
{"error":"Validation error","code":2003,"errors":{"smpAttr:1559":"Please specify a value for the Grid name."}}
```

**Comment by simonrolph** [comment]
Maybe it should be that when an attribute is removed it is made 'not required' at the same time

**Comment by johnvanbreda** [comment]
Now fixed. If you didn't create the attribute the system won't have permissions, so a warning is shown when you save a layout with a removed required attribute.
