### ISSUE TITLE
Non-present records with custom attribute data is lost

### ISSUE THREAD

**Issue by simonrolph** [Sheffield-Rotherham-Wildlife-Trust/NatureCounts#73]
When editing a record (or equally inputting new data)
![image](https://user-images.githubusercontent.com/17750766/121492348-b611d500-c9ce-11eb-9999-d891598bfa37.png)

![image](https://user-images.githubusercontent.com/17750766/121492515-da6db180-c9ce-11eb-9d92-06a41f3064e7.png)

Why is this an issue? (for this woodland condition form)
 - When inputting we ask volunteers to put 0 for the species cover for the invasive species to confirm that they have checked for species - we are currently losing this data
 - for reporting, when we process the data we'll have to do an extra computational step to check if the invasive species appear in the species lists for each grid square

Also, this is a case where we would want absence records to be created because we are doing exhaustive searches. However there may be other survey forms where this is not the case.

Maybe we need an 'Absent' tick box as well as the 'Present' tick box?

**Comment by johnvanbreda** [comment]
Would it work to allow a mode where the Present column is not shown and the system automatically includes the row as a record if any of the data values are set?

Or, we could have it so it remains as now, but the row is included if the Present box is ticked, or another field in the row has a value. We should be able to get it to flag the row as "zero abundance" if species cover is set to 0 (i.e. a null record).

**Comment by simonrolph** [comment]
The main concern is that record with a 0 species cover, which may be invasive species, that those records don't end up on the NBN without the attached meta data and mislead about the presence of invasive species.

I think it make sense to keep the 'present' column. There are custom survey forms which may not have any extra occurrence attributes, or the occurrence attributes may not apply to every species on the checklist.

I think your latter suggestion is best. We want to keep the data even if the present box isn't ticked. For example someone might have forgotten to tick present then we can go back and check the data and tick present without losing the rest of the occurrence data. But keep the 'Present' column.

Still has that concern about zero abundance records not being flagged. Could we add (or use existing) a boolean attribute (that can be added though the usual 'add an existing attribute' survey builder interface) that marks them as "zero abundance" records? Rather than having to set up zero-abundance criteria for specific attributes?

**Comment by johnvanbreda** [comment]
What about:
1. Add option to show a column "Absent" which links to the built in occurrence.zero_abundance field. It's important to use this field rather than a custom attribute as it triggers other functionality, like strike-through text on iRecord's explore pages.
2. Absent and present are mutually exclusive.
3. If any other data exist in a row but absent and present aren't ticked, then it triggers a validation error when you try to save.

**Comment by simonrolph** [comment]
Yes, that sounds perfect

**Comment by johnvanbreda** [comment]
There is now a new @absenceCol setting for the species_checklist control in the develop branch of the code.

**Comment by johnvanbreda** [comment]
Now deployed. See "Include an absence checkbox column" setting on the grid's block config.
