### ISSUE TITLE
Table for viewing sample data

### ISSUE THREAD

**Issue by simonrolph** [Sheffield-Rotherham-Wildlife-Trust/NatureCounts#77]
Viewing samples from the surveys is difficult on the 'all records' / 'my records' occurrence view pages. 

Use case: which survey grids has the data already been entered for? Quick access if I want to edit the sample for a particular survey square.

Need a report that produces table of sample attributes based on a given survey dataset + has edit button to go directly to editing that full sample

The best I could do was: https://record.wildsheffield.com/node/68 using a report library/samples/samples_list_2 

![image](https://user-images.githubusercontent.com/17750766/121562258-2f321c00-ca11-11eb-90d7-b8d05bc792e7.png)

But it doesn't have the custom sample attributes.

I need warehouse access to add our own reports?

Hardly any of the other sample reports in library/samples seemed to work- they would hang for a long time

**Comment by simonrolph** [comment]
Also the pagination on the library/samples/samples_list_2 report is wrong. Presumably it is counting occurrences and not samples

![image](https://user-images.githubusercontent.com/17750766/121561870-cfd40c00-ca10-11eb-8137-bf1510afbf94.png)

**Comment by johnvanbreda** [comment]
The pagination is now fixed. 

I've also implemented a lot of fixes around editing forms based on the sample_id (rather than the occurrence ID) which included upgrades to the REST API (since this is the first tool which bases record editing on REST rather than our old data services). So I think it is working. You will find that if you try to edit a sample entered on another user account you will get a warning and it won't load.

**Comment by simonrolph** [comment]
Thanks. Have updated that page https://record.wildsheffield.com/survey-forms/data on SRWT'S NC site with url alias, menu link and correct permissions. It's not perfect and may have to add more columns to the `smpattrs= ` every now and then. Other than that it serves the purpose of being able to view samples in a table.

I tried to add a 'My sample data' page using the `Samples list for a CMS user` report but doesn't seem to work. I tested it on NC and on the warehouse at https://warehouse1.indicia.org.uk/index.php/report_viewer/load?report_name=library%2Fsamples%2Fsamples_list_for_cms_user with my user ID of 124260 and the woodland condition spring survey dataset but no luck. Any ideas?

**Comment by johnvanbreda** [comment]
@simonrolph The Samples list for a CMS user report works for cases where the Drupal user ID gets stored against the record using a custom attribute. This is a legacy approach as now we normally use the Easy Login module to link the record's user_id to a warehouse account, which is then linked to the Drupal profile via a profile field. 

If you request the first page of a report, PostgreSQL's optimiser may not realise there isn't actually a page of data to load. This results in a table scan on 20m+ records and therefore a timeout. 

If you want to let me know the specification of what you want to achieve (columns, sort and parameters) I can either suggest a report for you or tweak one for your needs.

**Comment by simonrolph** [comment]
Ok thanks for the info.

It would be useful to have a version of the survey data report:
![image](https://user-images.githubusercontent.com/17750766/127832671-8f6ceaa6-b3fc-41ea-8821-b5062f3ab437.png)

Which only shows the data of the person who is logged in

Also the site code and sample method columns aren't used so would ideally get rid of them but isn't a major issue.

Are equivalent reports also do-able through the customisable elasticsearch report?

**Comment by johnvanbreda** [comment]
Currently the Elasticsearch reports can only report on samples that have occurrences - any that are empty lists won't be returned. Changing this is in the pipeline but it's not an insignificant change.

You can remove columns from this report - first you need to know the column name attribute from the report. Either by finding the XML file, clicking More Info on the Edit tab, - or a quick way is to inspect the column header and the HTML id of the <th> element will contain the column name (after grid-nn-th-). In this case the code column is just called "code". Now you can edit the page, find the link "Add column to columns list", Add property - fieldname, then enter "code". Now add property - visible and leave it unchecked. You may find that clicking View source under the JSON editor ensures the changes "stick" - we are using a 3rd party JSON editor and sometimes I find changes don't take effect unless I do this. Finally, save the page and the column should be hidden.

The report in use here doesn't have a user filter, but samples_list_for_warehouse_user2.xml does and is broadly similar. We could also set up a tweaked version of either of these reports if needs be.

**Comment by simonrolph** [comment]
Thanks John. I must have missed the samples_list_for_warehouse_user2.xml report, works great. Have removed columns I didn't want visible. I'm happy with the pages now.
