### ISSUE TITLE
clicking on edit record (of a record uploaded by csv uploader) on explore all records doesn't take you to the right url

### ISSUE THREAD

**Issue by simonrolph** [Sheffield-Rotherham-Wildlife-Trust/NatureCounts#96]
It takes you to: https://record.nottinghamshirewildlife.org/?occurrence_id=21087295

Whereas if you go to view recorod: https://record.nottinghamshirewildlife.org/details/record?occurrence_id=21087295
then click on edit it takes you to: https://record.nottinghamshirewildlife.org/record/list-of-records?occurrence_id=21087295

**Comment by simonrolph** [comment]
Looking at the actions code:

```
{
    "iconClass":"fas fa-edit", 
    "path":"{rootFolder}[metadata.input_form]",
    "title":"Edit this record (right click for option to open in new tab)",
    "urlParams":{
      "occurrence_id":"[id]"
    }
```

Something is wrong with `metadata.input_form` for csv uploaded records?

**Comment by johnvanbreda** [comment]
Imported records don't have an input_form set, but you can use tokenDefaults to apply a default: https://indicia-docs.readthedocs.io/en/latest/site-building/iform/helpers/elasticsearch-report-helper.html#id4. Here's an example from iRecord:
```
@actions=<!--[
  {
    "iconClass":"far fa-file-alt", 
    "path":"{rootFolder}record-details",
    "title":"View record details (right click for option to open in new tab)",
    "urlParams":{
      "occurrence_id":"[id]"
    }
  },
  {
    "iconClass":"fas fa-edit", 
    "path":"{rootFolder}[metadata.input_form]",
    "tokenDefaults":{
      "[metadata.input_form]": "edit-generic-record"
    },
    "title":"Edit this record (right click for option to open in new tab)",
    "urlParams":{
      "occurrence_id":"[id]"
    }
  }
]
-->
```

**Comment by simonrolph** [comment]
Thanks John.

To do:

Add

```
"tokenDefaults":{
      "[metadata.input_form]": "record/list-of-records"
    },
```

after line `"path":"{rootFolder}[metadata.input_form]",`

to:

- My records
- All record
- Activity records

but

Remove the edit button for page: explore all records (including iRecord)

for

- [ ] SRWT
- [ ] YWT
- [ ] MWT
- [ ] NorthWT
- [ ] HWT
- [ ] NottsWT
